// import React from "react";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ToastContainer, toast } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
// import ThemeProvider from "../components/theme-provider";
// import { cn } from "../lib/utils";
// import SideBar from "../components/sidebar/page";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={cn(inter.className, "bottom-0")}>
//         <ToastContainer />
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <div className="grid grid-cols-12">
//             <div className="col-span-1">
//               <SideBar />
//             </div>
//             <div className="col-span-11 w-3/5 mx-auto pt-20 px-10">
//               {children}
//             </div>
//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import React from "react";
import Test from "./context/auth";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ThemeProvider from "../components/theme-provider";
import { cn } from "../lib/utils";
import SideBar from "../components/sidebar/page";
import { AuthContext, AuthProvider } from "../app/context/auth-context";
import Auth from "./context/auth";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(leagueSpartan.className, "bottom-0")}>
        <AuthProvider>
          <ToastContainer />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Auth>{children}</Auth>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
